#!/bin/bash

NOW=$(date +%s)
RES=300
SRC=Flatbed    #Flatbed|ADF
MODE=Color     #Gray|Color|Lineart(?)
TYPE=tiff    
NEWTYPE=jpeg
FINTYPE=pdf
QUALITY=35

cd $NAUTILUS_SCRIPT_CURRENT_URI

echo scan$NOW-%d.$TYPE

#scanadf --no-overwrite --mode $MODE --resolution $RES --source $SRC -o scan$NOW-%d.$TYPE
scanimage --batch-count=1 --batch=scan$NOW-%d.$TYPE --progress --format=$TYPE --mode $MODE --source $SRC --resolution $RES

for fullfilename in *.$TYPE  #loop through all the files
  do
  origname=$(basename $fullfilename)
  compressedname=$(echo $origname | sed -e "s/\.$TYPE/\.$NEWTYPE/g")
  pdfname=$(echo $origname | sed -e "s/\.$TYPE/\.$FINTYPE/g")
  #tiff to jpeg, trim away anything that might be missing
  convert -trim -quality $QUALITY $origname $compressedname    
  convert $compressedname $pdfname

  #if the pdf file exists get rid of the tiff file and the jpeg file
  if [ -f "$compressedname" ]; then
     rm $origname
     rm $compressedname     
     echo Removed $TYPE and $NEWTYPE file
  fi
done
