#!/bin/bash

NOW=$(date +%s)
RES=300
SRC=ADF
MODE=Gray
TYPE=tiff    
NEWTYPE=jpeg
FINTYPE=pdf

cd $NAUTILUS_SCRIPT_CURRENT_URI

echo scan$NOW-%d.$TYPE

#scanadf --no-overwrite --mode $MODE --resolution $RES --source $SRC -o scan$NOW-%d.$TYPE
scanimage --batch=scan$NOW-%d.$TYPE --progress --format=$TYPE --mode $MODE --resolution $RES --source $SRC

for fullfilename in *.$TYPE  #loop through all the files
  do
  origname=$(basename $fullfilename)
  compressedname=$(echo $origname | sed -e "s/\.$TYPE/\.$NEWTYPE/g")
  pdfname=$(echo $origname | sed -e "s/\.$TYPE/\.$FINTYPE/g")
  #tiff to jpeg
  convert $origname -transparent-color \#FFFFFF00 $compressedname    
  convert $compressedname $pdfname

  #if the pdf file exists get rid of the tiff file and the jpeg file
  if [ -f "$compressedname" ]; then
     rm $origname
     rm $compressedname     
     echo Removed $TYPE and $NEWTYPE file
  fi
done
